### ISSUE TITLE
Conditional Enabling

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#10]
Should Emmet only be enabled for HTML / CSS compatible languages? 
Is there a good way to limit Emmet activation based on the active language in a CodeMirror 6 instance?

**Comment by sergeche** [comment]
It’s already limited to HTML and CSS syntaxes. Also, it’s up to developer to not include `abbreviationTracker()` extension to unsupported syntaxes

**Comment by shshaw** [comment]
Yeah... Okay. I think we manually enable/disable it on CodeMirror 5 based on supported syntaxes already, so I'll just have to adapt that.

Thanks for the quick response.
