### ISSUE TITLE
Make CSS autocomplete option position configurable/dynamic to better handle conflicts with built-in autocomplete

### ISSUE THREAD

**Issue by sergeichestakov** [emmetio/codemirror6-plugin#11]
It seems that the Emmet extension currently conflicts with the [built-in CSS autocomplete results](https://github.com/codemirror/lang-css/blob/main/src/complete.ts) and is always rendered at the top no matter how relevant it is.

I did some digging into the code and found that Emmet's CSS completion source always sets the [filter flag to false](https://github.com/emmetio/codemirror6-plugin/blob/9d074aec6f5e1eccf7796a7de7469fcbf42e8c0e/src/tracker/index.ts#L46) and returns a [boost of 99](https://github.com/emmetio/codemirror6-plugin/blob/9d074aec6f5e1eccf7796a7de7469fcbf42e8c0e/src/tracker/index.ts#L691) for autocomplete options which causes them to be weighted above all other autocomplete options that may be present (e.g. the default ones).

It would be nice if this was configurable so that Emmet does not always render above other autocomplete options, especially when it may not be the most relevant.

**Comment by sergeche** [comment]
In v0.2.0, there’s a new `completionBoost` option for that. You can either pass it to `abbreviationTracker()` extension or use `emmetConfig` facet instead, as described in #13

**Comment by sergeichestakov** [comment]
Awesome, thanks! I'll give it a try later. However, I think the fact that the filter flag is set to false will still lead to the Emmet results being rendered above all unfiltered options so this may not completely address our use case. From [the docs](https://codemirror.net/docs/ref/#autocomplete.CompletionResult.filter):

> By default, the library filters and scores completions. Set filter to false to disable this, and cause your completions to all be included, in the order they were given. When there are other sources, unfiltered completions appear at the top of the list of completions.

**Comment by sergeche** [comment]
`filter` option is required to properly recalculate completions when user types (e.g. `p` → `p1`). Without this option, CM requires a list of static completions which will be filtered by CM automatically
