### ISSUE TITLE
When used in nextJS setup, it works on dev but when you build it does not work.

### ISSUE THREAD

**Issue by ramisich** [emmetio/codemirror6-plugin#17]
I basically copied the source and used it in a page in next js based app. when on dev (yarn dev in nextjs) it works fine, but when you build it you get the following error. Do you know what the problem is?

Im doing expandAbbreviation. Same code as yours.

 Cannot read properties of undefined (reading '0')
    at i (abbreviation.es.js:12:1)
    at l (abbreviation.es.js:24:1)
    at abbreviation.es.js:282:1
    at abbreviation.es.js:290:1
    at e (abbreviation.es.js:136:1)
    at abbreviation.es.js:79:1
    at F (abbreviation.es.js:47:1)
    at emmet.es.js:1443:16
    at t5 (emmet.es.js:1457:1)
    at et (emmet.ts:48:12)

**Comment by sergeche** [comment]
I guess this error due to your next.js setup. CM6 embeds perfectly as npm module in a number of projects

**Comment by ramisich** [comment]
Yes. Thanks for the great work. I solved it by modifying the optmiziation (minify) config of nextjs and now it all works. All good.
