### ISSUE TITLE
Ignore expand abbreviation if multiple lines selected

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#21]
If you have Tab mapped to expand abbreviation and indent, most of the time it seems to work fine, but occasionally if your cursor is inside of some text and you tab to indent, Emmet tries to expand that first word as an abbreviation.

Example: if you have the cursor on `<p>`, Emmet ignores and indent works properly.

https://github.com/emmetio/codemirror6-plugin/assets/777155/310173af-7c6c-4523-9dea-c03d191c1ed9

Example: If you have your cursor inside on some text, it expands strangely.

https://github.com/emmetio/codemirror6-plugin/assets/777155/0d423e0a-b4d5-4115-b69c-34a7ac14c6c4

Perhaps the Emmet expansion should not run if the selection includes a range > 0?

**Comment by sergeche** [comment]
I guess you’ve used `expandAbbreviation` command as tab key handler? You should use abbreviation tracker instead as described in README, it contains all the required logic to handle Tab key.

The reason to expand abbreviation if range > 0 is to allow user to select specific text and expand it as abbreviation (in case if abbreviation extraction doesn’t work as expected)

**Comment by shshaw** [comment]
Hm, I currently have _both_, which may be part of the problem. I think I had the Tab keymap from the previous version and added abbreviationTracker when that was available. 

<img width="552" alt="Screenshot 2023-10-04 at 10 03 43 AM" src="https://github.com/emmetio/codemirror6-plugin/assets/777155/a2a87567-a305-46e8-bf99-de948f5e73ac">

To clarify: If you use `abbreviationTracker`, you do not need a separate keymap for `expandAbbreviation`?

**Comment by shshaw** [comment]
Okay, I did get this working with just `abbreviationTracker`. However, I had to set this extension to `Prec.high` in order for the Tab keymap to run ahead of the `indentWithTab` keymap

```
    Prec.high( abbreviationTracker( ... ) )
```

If you're using some of the CodeMirror default extension lists, you may need that extra Precedence bump.

**Comment by sergeche** [comment]
> To clarify: If you use abbreviationTracker, you do not need a separate keymap for expandAbbreviation?

No, `expandAbbreviation` action should be used in case you want to expand abbreviation in some unsupported syntax like Markdown or Go (why not?). In supported syntaxes, if you want to expand by Tab, you should use abbreviation tracker since Tab key is very tricky to handle. Tracker contains all the logic to make it as smooth as possible

**Comment by shshaw** [comment]
Tricky. I think my current setup of mapping languages to certain syntaxes is sufficient for the languages we'll support. Thanks for clarifying.
