### ISSUE TITLE
Mount Preview to ShadowDOM root

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#22]
For [_reasons_](https://www.notion.so/codepen/February-2-8-2024-cac76c5c6e724706b730f4c800a852dd?pvs=4#4daee5aabe1c4bc3820bd1e585992045) we have to mount CodeMirror 6 in ShadowDOM (which CodeMirror 6 supports via the [`root` property of `EditorView`](https://codemirror.net/docs/ref/#view.EditorViewConfig.root).

Emmet overall works fine, but theme styles don't work in Emmet in the ShadowDOM since the Emmet Preview's `EditorView` is using the parent document instead of the ShadowDOM root.

A couple of ideas on how to solve the problem:
1. Use the parent `EditorView`'s `root` property when creating the preview `EditorView`, though it doesn't seem like `createPreview` gets the parent `EditorView` which could be referenced. 
2. Give an API to retrieve the preview `EditorView` to allow setting the `root` manually with [`setRoot`](https://codemirror.net/docs/ref/#view.EditorView.setRoot)

**Comment by sergeche** [comment]
Ok, I’ll try to explore how to attach styles for preview in ShadowDOM mode, seems to be a valid use case

**Comment by sergeche** [comment]
Added `root` option for [preview config](https://github.com/emmetio/codemirror6-plugin/blob/main/src/lib/config.ts#L20) in v0.3.2.

**Comment by shshaw** [comment]
Haven't been able to get this integrated yet, but that does seem like what I need. Would be great if it could automatically be inherited from the parent, but doesn't seem like CodeMirror even has that available. Closing out for now, if I can get it working or run into trouble, I'll update. Thanks!
