### ISSUE TITLE
Known Syntaxes as Enum

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#23]
Could the [`EmmetKnownSyntax` list](https://github.com/emmetio/codemirror6-plugin/blob/main/src/lib/types.ts#L4-L6) be converted to an `enum` and exported so those values can be referenced?

Right now in my codebase I'm matching up the CodeMirror 6 Editor's language to an EmmetKnownSyntax but I'm just using a string. Having that value as an enum would ensure matching the exact values _and_ allow authors to know which syntaxes are supported just by referencing the enum.

**Comment by chriscoyier** [comment]
Hey Sergey, 

Mind a version bump to 0.3.1 or something so we can use this?

**Comment by sergeche** [comment]
Done, check out v0.3.1 version

**Comment by shshaw** [comment]
Confirmed working on 0.3.1. Thanks, @sergeche!
