### ISSUE TITLE
Markup Snippets not working in Vue

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#25]
CSS snippets seem to be working in Vue, but Markup snippets don't. Am I missing something or is this a bug?

https://github.com/emmetio/codemirror6-plugin/assets/777155/5089dae5-6260-4bcf-acb2-abfd2eb55b6d

**Comment by shshaw** [comment]
Regular expansions `div*5` seem to work, but not custom markup snippets.
<img width="153" alt="Screenshot 2024-03-14 at 11 48 26 AM" src="https://github.com/emmetio/codemirror6-plugin/assets/777155/060a4996-165c-43eb-9335-e40b9ba42f8b">

**Comment by sergeche** [comment]
Will check this out. Do you use standard Vue syntax highlighter?

**Comment by shshaw** [comment]
I'm using the official @codemirror/lang-vue as loaded from @codemirror/language-data: https://github.com/codemirror/language-data/blob/main/src/language-data.ts#L995-L1001

**Comment by sergeche** [comment]
Can you provide Emmet config you use for Vue editor? Seems to work fine for me

**Comment by shshaw** [comment]
Confirmed that snippets seem to be working now.

This may have been a problem with an improperly escaped snippet causing the markdown snippets to not work. The snippet was just text `words with spaces` without any quotes or escaping, which seemed to make all the snippets not work. I'm looking to add some validation/protection around this. That may be a problem with our snippet setup code, not Emmet, but let me know if you have any guidance on that.

Thanks for checking 👍
