### ISSUE TITLE
Limit Emmet CSS autocomplete suggestions

### ISSUE THREAD

**Issue by shshaw** [emmetio/codemirror6-plugin#27]
Are there any ways to tone down Emmet's autocomplete suggestions, particularly for CSS?

Right now, typing out `color: CanvasColor` (valid CSS) has a suggestion for `Emmet abbreviation`.

<img width="454" alt="Screenshot 2024-07-03 at 2 14 57 PM" src="https://github.com/emmetio/codemirror6-plugin/assets/777155/7074ce45-cd69-4ff5-b3d0-b442ccb5ecba">

If you accept the completion, about half of the time it ends up with something like this:
<img width="233" alt="Screenshot 2024-07-03 at 2 17 40 PM" src="https://github.com/emmetio/codemirror6-plugin/assets/777155/ab872f3c-048c-4454-9518-11edc495aab8">

The other half of the time it doesn't do... anything?

Neither is ideal. If Emmet doesn't have anything helpful to add, can it not offer an autocompletion?

**Comment by sergeche** [comment]
Hmm, definitely it’s a but, Emmet should’t provide any completions in this case. Will take a look

**Comment by sergeche** [comment]
Should be fixed in v0.3.2

**Comment by shshaw** [comment]
It does seem to be better about not jacking up the expansion, though it does still weirdly offer to expand the property as an abbreviation even after you've given the property a value. Hitting enter to complex the expansion results in the value getting bumped outside the semicolon.

<img width="386" alt="Screenshot 2024-08-05 at 11 21 54 AM" src="https://github.com/user-attachments/assets/26a5d4e0-1a30-480b-965a-390931be8c39">

https://github.com/user-attachments/assets/a41f49c2-a15e-4adb-b957-4d90f38b107e

**Comment by sergeche** [comment]
Oh, it’s an issue with abbreviation tracking, it should stop right after abbreviation becomes invalid. Will check it out

**Comment by shshaw** [comment]
Thanks, Sergey!

**Comment by shshaw** [comment]
Another example of the abbreviation tracking problem: Emmet tries to expand `max-inline-size: 300px;` and for whatever reason, that expands to `max: inline size; 300px;`

https://github.com/user-attachments/assets/49bdc37f-879d-4104-a237-52d73b4e74e0

**Comment by sergeche** [comment]
Oh, that’s weird, will check it out

**Comment by sergeche** [comment]
Just published v0.3.3 that should have this issue fixed. Note that for `max-inline-size` example, you should set new option `'stylesheet.strictMatch': true` (see main.ts for example), this will prevent Emmet to convert unmatched abbreviations to CSS properties

**Comment by shshaw** [comment]
Even with the new version and option set, there are the occasional odd suggestions. Any way to improve that?

![Screenshot 2024-10-03 at 4 17 23 PM](https://github.com/user-attachments/assets/ef1fedc5-7e2c-42c9-a609-c60bc6fbdb5c)

![image](https://github.com/user-attachments/assets/53d0d059-3c59-4b4f-bf7d-379cad089eda)

**Comment by sergeche** [comment]
@shshaw can’t reproduce that on demo page of current repo.  Emmet completion disappers when I type `font`. Maybe you can demo a video?

Also please make sure you have most recent core Emmet package `emmet@2.4.11`

**Comment by shshaw** [comment]
I ensured all packages are updated. Same behavior on 2.4.11
It's definitely better; I can't get `font-weight: 500;` to expand oddly, but Emmet is still offering to expand `font-weight:` to `font: weight;` until you add a space after the colon `:`. Same with `background-color:` and other dash separated properties.

<img width="391" alt="Screenshot 2024-10-18 at 7 17 04 AM" src="https://github.com/user-attachments/assets/a8c544b9-0c98-4cb7-8078-0dd61dc18ba7">

https://github.com/user-attachments/assets/6039fc9e-431f-47ee-b86f-34d40033410d

It looks like that's the way Emmet behaves in CodeMirror 5 so I think this isn't technically a bug, it's just a bit more visible now in the CM6 autocomplete menu. 

https://github.com/user-attachments/assets/ce7857b2-4cb0-4661-ab32-cd3a9cdedb1c

I think I'll close this for now and we can see if we get any user feedback about it. Thanks, Sergey!
