### ISSUE TITLE
Outdated peerDependencies

### ISSUE THREAD

**Issue by chriscoyier** [emmetio/codemirror6-plugin#28]
This plugin has a couple of CodeMirror peerDeps:

https://github.com/emmetio/codemirror6-plugin/blob/main/package.json#L25-L26

Specifically `@codemirror/highlight` and `@codemirror/history`. But both of them are deprecated:

- https://www.npmjs.com/package/@codemirror/history
- https://www.npmjs.com/package/@codemirror/highlight

Could these be updated to the other packages or removed if not needed?

**Comment by sergeche** [comment]
OK, will check it out in a few days and update/remove deps

**Comment by shshaw** [comment]
It doesn't look like `@codemirror/highlight` or `@codemirror/history` are even used. They're in the package.json but not referenced elsewhere in the code.

**Comment by sergeche** [comment]
Removed unused dependencies in v0.3.2

**Comment by shshaw** [comment]
Thanks, @sergeche!
