### ISSUE TITLE
An Invalid Custom Snippet Breaks Other Snippets That Start with the Same Starting Name

### ISSUE THREAD

**Issue by chriscoyier** [emmetio/codemirror6-plugin#30]
Weird one for you here!

If you have custom snippets like this...

```
              config: {
                markup: {
                  snippets: {
                    foo: "invalid snippet",
                    // The above will break this VALID snippet below:
                    foo2: "button",
                  },
                },
```

It makes sense that `foo` doesn't work, because that's not a valid Emmet abbreviation. But just by being there, it makes the snippet `foo2` not work either.

**Comment by sergeche** [comment]
Fixed in v.2.4.10 in `emmet` package yet unable to verify, npm says it’s not published yet. Cach you check if you’re able to install v.2.4.10?

**Comment by sergeche** [comment]
Should be fixed in v.0.3.4

**Comment by chriscoyier** [comment]
Confirmed fixed.
