### ISSUE TITLE
Untranspiled code

### ISSUE THREAD

**Issue by masad-frost** [emmetio/codemirror6-plugin#6]
Hey Sergey, we noticed that there's untranspiled code in the published package and was wondering if you can publish a non-esnext target https://github.com/emmetio/codemirror6-plugin/blob/main/vite.config.ts#L7?

We use codemirror's `cm-buildhelper` for prod builds and works well for us, for example: https://github.com/replit/codemirror-vscode-keymap/blob/master/package.json#L22. We still use vite for local development (you can click run on replit and you can see how it runs on replit with vite https://github.com/replit/codemirror-vscode-keymap).

**Comment by masad-frost** [comment]
FWIW cm-buildhelpers uses `rollup` under the hood and creates an

**Comment by sergeche** [comment]
You need a CommonJS module? Or just transpile module to lower ES syntax?

**Comment by masad-frost** [comment]
Es module is fine, the thing tripping up our clients is the optional chaining. Compiling to es6 would be ideal for us. Thank you!

**Comment by sergeche** [comment]
Downgraded output to es2017 in v0.0.7

**Comment by masad-frost** [comment]
Thank you!
