### ISSUE TITLE
preview rendering inside strings

### ISSUE THREAD

**Issue by Bardia95** [emmetio/codemirror6-plugin#8]
Preview should not render when cursor is inside a string

See below for example from replit.com which uses this plugin
![image](https://user-images.githubusercontent.com/24982590/168416879-20bd5b8a-0ecd-4ba1-a69f-3ba36952dea2.png)

**Comment by sergeichestakov** [comment]
cc @sergeche just wanted to flag this issue as we've been seeing reports complaining about this internally - any chance we can get this fixed as part of the next patch?

I can also take a look and open a PR if you're busy just let me know!
